import Head from "next/head";
import React from "react";
import { Breadcrumbs, IBreadcrumbLink } from "../Breadcrumbs";
import TopNav from "../TopNav";

interface Props {
  breadCrumbs?: Array<IBreadcrumbLink>;
  pageTitle?: string;
  children?: any;
}

export const Layout: React.FC<Props> = ({
  children,
  pageTitle,
  breadCrumbs,
}) => {
  const title = `${pageTitle || "The monitoring app"}  - Perfectionist`;
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="max-w-7xl m-auto font-bodyCopy">
        <TopNav />
        {breadCrumbs && (
          <div className="mt-4">
            <Breadcrumbs links={breadCrumbs} />
          </div>
        )}
        <div className="mt-4">{children}</div>
      </main>
    </div>
  );
};
